Update _gameactivity.py
efroemling/ballistica pull request #537
Opened 2022-10-24 16:46 UTC by fraq-sss

## Steps

- [ ] Write a good description of what your PR does (and WHY it does it).
- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a CHANGELOG entry if your change is non-trivial.
- [ ] Ensure `make preflight` completes successfully.

## Description

## Type of Changes

|     | Type                   |
|-----|------------------------|
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Related Issue

2022-10-25 14:43 UTC, Dliwk requested changes

2022-10-25 14:43 UTC, Dliwk commented on assets/src/ba_data/python/ba/_gameactivity.py
> +                position, angle or random.uniform(0, 360)
In case `angle` is 0 that won't work as expected.
```py
>>> 0 or 1337
1337
```

2022-10-25 14:43 UTC, Dliwk commented on assets/src/ba_data/python/ba/_gameactivity.py
> +                position, angle or random.uniform(0, 360)
But 'Optional or Default' syntax looks good in general. Note that it simply evaluates to `x if bool(x) else y` https://stackoverflow.com/a/3914686/17444908

2023-01-18 01:34 UTC, efroemling commented
Thanks for the contribution, but I think I'll pass on this one.

It does certainly make the lines look cleaner, but as @Dliwk mentioned above there can be unexpected corner cases where a  user might want to explicitly pass a value that evaluates to False. I've been burned a few times doing that sort of thing myself. For instance, if we set up something like:
`starting_powerups = passed_powerups or ['sword', 'club', 'rockets']`
..it looks reasonable but we've now made it impossible to start with an empty set of powerups.

So these days whenever I'm treating None as a special case I try to explicitly do `foo is None` instead of a bool evaluation even if that means the code is less pretty. Under the hood, 'is' simply compares the two objects' pointers so it shouldn't be too inefficient.

2023-01-18 01:34 UTC, closed without merging