A Small but Fun Change
efroemling/ballistica pull request #761
Opened 2024-12-11 08:08 UTC by vishal332008

It's fun.

https://github.com/user-attachments/assets/630b5431-e23e-4ca0-ba0e-783c2afec43f

2024-12-11 09:01 UTC, EraOSBeta approved these changes

2025-01-15 11:50 UTC, EraOSBeta requested changes
Make it select a random related noise from a random character instead of an immutable noise from Spaz.

2025-01-15 16:07 UTC, EraOSBeta approved these changes

2025-01-17 02:14 UTC, efroemling commented
Thaaaanks!

2025-01-17 02:14 UTC, merged